# kind-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind # The cluster name
nodes:
- role: control-plane
  image: kindest/node:v1.29.2
  # Control plane usually doesn't need an env label as it won't run your apps
- role: worker
  image: kindest/node:v1.29.2
  # Explicitly naming the worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: dev-worker-1
- role: worker
  image: kindest/node:v1.29.2
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: dev-worker-2