apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
  namespace: avro-schema-registry
data:
  schema-registry.properties: |
    listeners=http://0.0.0.0:8081
    kafkastore.bootstrap.servers=PLAINTEXT://dev-kafka-kafka-bootstrap.kafka:9092
    kafkastore.topic=_schemas
    schema.registry.group.id=schema-registry
    inter.instance.protocol=http
    compatibility.level=BACKWARD
