apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-configmap-schema-registry.yaml
  - 03-deployment-schema-registry.yaml
  - 04-service-schema-registry.yaml
