apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-schema-registry
  namespace: prodenv-avro-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-schema-registry
  template:
    metadata:
      labels:
        app: prod-schema-registry
    spec:
      nodeSelector:
        env: prod  # This matches the label we created in Task 1
      enableServiceLinks: false   # <<< THIS IS THE FIX
      imagePullSecrets:
        - name: dockerhub-pull
      containers:
        - name: prod-schema-registry
          image: commodore95/quant_data_platform_repository:confluentinc-cp-schema-registry-7.6.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "prod-kafka-kafka-bootstrap.prodenv-kafka:9092"